inputs:
  Messages:
    stream: MESSAGES # messages table in our schema
    transport:
      name: file
      config: 
        path: "/database-stream-processor/demo/hello-world/messages.csv"
        follow: true

    format:
      name: csv
          
  Records:
    stream: RECORDS # records table in our schema
    transport:
      name: file
      config: 
        path: "/database-stream-processor/demo/hello-world/records.csv"
        follow: true

    format:
      name: csv

outputs:
  Filtered:
    stream: MESSAGE_COMBINER
    transport:
      name: file
      config: 
        path: "/database-stream-processor/demo/hello-world/matches.csv"

    format:
      name: csv
